spring:
  autoconfigure:
    # 데이터베이스 아직 선정 안 함
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 #최적화 옵션

logging.level:
  org.hibernate.SQL: debug